# using nginx as layer 
FROM nginx:latest
# set working directory to be /usr..
WORKDIR /usr/share/nginx/html
# copy our index.htmk to the index.html in the working directory
COPY index.html index.html